version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app  # Mounts the local directory to the container
    ports:
      - "5000:5000"  # Expose port 5000
    depends_on:
      - mongo  # Ensures MongoDB starts before the app
    environment:
      - MONGO_DB=${MONGO_DB}  # Pass the MongoDB connection string from the .env file
    image: vehicle_allocation_app
    container_name: vehicle_allocation_backend
    command: uvicorn index:app --reload --host 0.0.0.0 --port 5000

  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
